---
- hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: Collect all BIG-IP information
      bigip_device_info:
        gather_subset:
          - all
        provider:
          server: "{{ inventory_hostname }}"
          validate_certs: no
      delegate_to: localhost
